name: flutter_todo
description: 'Todo app made via Flutter.'
publish_to: 'none'
version: 1.2.0
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  intl: ^0.19.0
  go_router: ^14.3.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
